/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CylinderSemantic.GUI;

import CylinderSemantic.Handles.CylinderHandle;

import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Vector;

/**
 *
 * @author chenjinguyen
 */
public class CylinderSemanticGUI extends javax.swing.JFrame {
    CylinderHandle cylinderHandle = new CylinderHandle();
    ArrayList<JTextField> txtElements = new ArrayList<JTextField>();

    /**
     * Creates new form MainUI
     */
    public CylinderSemanticGUI() {
        initComponents();
        initDatas();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        imgCylinder = new javax.swing.JLabel();
        pnResult = new javax.swing.JPanel();
        cbSelectElement = new javax.swing.JComboBox<>();
        lbResult = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        btnTinh = new javax.swing.JButton();
        btnNhapLai = new javax.swing.JButton();
        btnThongTin = new javax.swing.JButton();
        pnElements = new javax.swing.JPanel();
        lbh = new javax.swing.JLabel();
        txth = new javax.swing.JTextField();
        lbr = new javax.swing.JLabel();
        txtr = new javax.swing.JTextField();
        lbSxq = new javax.swing.JLabel();
        txtSxq = new javax.swing.JTextField();
        lbStp = new javax.swing.JLabel();
        txtStp = new javax.swing.JTextField();
        lbSo = new javax.swing.JLabel();
        txtSo = new javax.swing.JTextField();
        lbCo = new javax.swing.JLabel();
        txtCo = new javax.swing.JTextField();
        lbSq = new javax.swing.JLabel();
        txtSq = new javax.swing.JTextField();
        lbV = new javax.swing.JLabel();
        txtV = new javax.swing.JTextField();
        imgEleAndEqua = new javax.swing.JLabel();
        pnRTable = new javax.swing.JPanel();
        scpRTable = new javax.swing.JScrollPane();
        tblRTable = new javax.swing.JTable();
        pnBuocGiai = new javax.swing.JPanel();
        scpBuocGiai = new javax.swing.JScrollPane();
        listBuocGiai = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bài Toán Tam Giác - Mạng Ngữ Nghĩa");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1125, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(1125, 750));

        lbTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbTitle.setText("BÀI TOÁN HÌNH LĂNG TRỤ - MẠNG NGỮ NGHĨA");

        imgCylinder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CylinderSemantic/Resources/hinhtru.jpg"))); // NOI18N

        pnResult.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tính Giá Trị", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        lbResult.setText("Kết Quả");

        txtResult.setEnabled(false);

        btnTinh.setText("Tính");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });

        btnNhapLai.setText("Nhập Lại");
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });

        btnThongTin.setText("Thông Tin");
        btnThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnResultLayout = new javax.swing.GroupLayout(pnResult);
        pnResult.setLayout(pnResultLayout);
        pnResultLayout.setHorizontalGroup(
            pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSelectElement, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnResultLayout.createSequentialGroup()
                        .addComponent(lbResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResult)
                        .addGap(91, 91, 91))
                    .addGroup(pnResultLayout.createSequentialGroup()
                        .addComponent(btnTinh)
                        .addGap(18, 18, 18)
                        .addComponent(btnNhapLai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnThongTin))))
        );
        pnResultLayout.setVerticalGroup(
            pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnResultLayout.createSequentialGroup()
                .addComponent(cbSelectElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResult)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinh)
                    .addComponent(btnNhapLai)
                    .addComponent(btnThongTin)))
        );

        pnElements.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CÁC YẾU TỐ TRONG HÌNH LĂNG TRỤ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N

        lbh.setText("h");

        txth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthKeyTyped(evt);
            }
        });

        lbr.setText("r");

        txtr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrKeyTyped(evt);
            }
        });

        lbSxq.setText("Sxq");

        txtSxq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSxqKeyTyped(evt);
            }
        });

        lbStp.setText("Stp");

        txtStp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStpKeyTyped(evt);
            }
        });

        lbSo.setText("So");

        txtSo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoKeyTyped(evt);
            }
        });

        lbCo.setText("Co");

        txtCo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoKeyTyped(evt);
            }
        });

        lbSq.setText("Sq");

        txtSq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSqKeyTyped(evt);
            }
        });

        lbV.setText("V");

        txtV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnElementsLayout = new javax.swing.GroupLayout(pnElements);
        pnElements.setLayout(pnElementsLayout);
        pnElementsLayout.setHorizontalGroup(
            pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnElementsLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnElementsLayout.createSequentialGroup()
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbStp)
                            .addComponent(lbSxq))
                        .addGap(23, 23, 23)
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSxq, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStp, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnElementsLayout.createSequentialGroup()
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbr)
                            .addComponent(lbh))
                        .addGap(39, 39, 39)
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txth, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtr, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69)
                .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnElementsLayout.createSequentialGroup()
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCo)
                            .addComponent(lbSo))
                        .addGap(21, 21, 21)
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnElementsLayout.createSequentialGroup()
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbV)
                            .addComponent(lbSq))
                        .addGap(23, 23, 23)
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSq, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtV, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        pnElementsLayout.setVerticalGroup(
            pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnElementsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnElementsLayout.createSequentialGroup()
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbh)
                            .addComponent(txth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbr)
                            .addComponent(txtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnElementsLayout.createSequentialGroup()
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSo)
                            .addComponent(txtSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCo)
                            .addComponent(txtCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnElementsLayout.createSequentialGroup()
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSxq)
                            .addComponent(txtSxq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbStp)
                            .addComponent(txtStp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnElementsLayout.createSequentialGroup()
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSq)
                            .addComponent(txtSq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbV)
                            .addComponent(txtV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imgEleAndEqua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CylinderSemantic/Resources/cthinhtru.jpg"))); // NOI18N
        imgEleAndEqua.setPreferredSize(new java.awt.Dimension(600, 394));

        pnRTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BẢNG QUAN HỆ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        tblRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scpRTable.setViewportView(tblRTable);

        javax.swing.GroupLayout pnRTableLayout = new javax.swing.GroupLayout(pnRTable);
        pnRTable.setLayout(pnRTableLayout);
        pnRTableLayout.setHorizontalGroup(
            pnRTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
            .addGroup(pnRTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnRTableLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scpRTable, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnRTableLayout.setVerticalGroup(
            pnRTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
            .addGroup(pnRTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnRTableLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scpRTable, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnBuocGiai.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CÁC BƯỚC GIẢI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        scpBuocGiai.setViewportView(listBuocGiai);

        javax.swing.GroupLayout pnBuocGiaiLayout = new javax.swing.GroupLayout(pnBuocGiai);
        pnBuocGiai.setLayout(pnBuocGiaiLayout);
        pnBuocGiaiLayout.setHorizontalGroup(
            pnBuocGiaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnBuocGiaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnBuocGiaiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scpBuocGiai, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnBuocGiaiLayout.setVerticalGroup(
            pnBuocGiaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
            .addGroup(pnBuocGiaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuocGiaiLayout.createSequentialGroup()
                    .addComponent(scpBuocGiai, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(imgCylinder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnBuocGiai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnElements, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgEleAndEqua, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTitle)
                .addGap(229, 229, 229))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(imgEleAndEqua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnRTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgCylinder)
                            .addComponent(pnResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnBuocGiai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        btnTinh();
    }//GEN-LAST:event_btnTinhActionPerformed

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
        btnNhapLai();
    }//GEN-LAST:event_btnNhapLaiActionPerformed

    private void btnThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinActionPerformed
        btnThongTin();
    }//GEN-LAST:event_btnThongTinActionPerformed

    private void txthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthKeyTyped
        checkNumber(evt,txth);
    }//GEN-LAST:event_txthKeyTyped

    private void txtrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrKeyTyped
        checkNumber(evt,txtr);
    }//GEN-LAST:event_txtrKeyTyped

    private void txtStpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStpKeyTyped
        checkNumber(evt,txtStp);
    }//GEN-LAST:event_txtStpKeyTyped

    private void txtSxqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSxqKeyTyped
        checkNumber(evt,txtSxq);
    }//GEN-LAST:event_txtSxqKeyTyped

    private void txtCoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoKeyTyped
        checkNumber(evt,txtCo);
    }//GEN-LAST:event_txtCoKeyTyped

    private void txtSoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoKeyTyped
        checkNumber(evt,txtSo);
    }//GEN-LAST:event_txtSoKeyTyped

    private void txtVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVKeyTyped
        checkNumber(evt,txtV);
    }//GEN-LAST:event_txtVKeyTyped

    private void txtSqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSqKeyTyped
        checkNumber(evt,txtSq);
    }//GEN-LAST:event_txtSqKeyTyped

    /**
     * Init Default Value when Program start
     */
    private void initDatas(){
        imgEleAndEqua.setIcon(new ImageIcon(cylinderHandle.imageCylinderSemanticChange().getScaledInstance(620, 408, Image.SCALE_DEFAULT)));
        txtElements.add(txth);
        txtElements.add(txtr);
        txtElements.add(txtCo);
        txtElements.add(txtSo);
        txtElements.add(txtSq);
        txtElements.add(txtSxq);
        txtElements.add(txtStp);
        txtElements.add(txtV);
        tblRTable.setEnabled(false);
        tblRTable.setDragEnabled(false);
        tblRTable.getTableHeader().setEnabled(false);
        String[] cbDatas = {"Giá Trị Cần Tính","h","r","Co","So","Sq","Sxq","Stp","V","Cq"};
        for (int i = 0; i < cbDatas.length; i++) {
            cbSelectElement.addItem(cbDatas[i]);
        }
        cylinderHandle.initRVTable();
        setRTable(cylinderHandle.getRTable());
    }

    /**
     * Action if Button Tinh Clicked
     */
    private void btnTinh(){
        setBuocGiai(null);
        txtResult.setText("");
        String selectElements = cbSelectElement.getSelectedItem().toString();
        if(!selectElements.equals("Giá Trị Cần Tính")){
            cylinderHandle.start(txtElements,txtResult,selectElements,imgEleAndEqua);
            setRTable(cylinderHandle.getRTable());
            setBuocGiai(cylinderHandle.getLstBuocGiai());
        }else{
            JOptionPane.showMessageDialog(null,"Vui lòng chọn yếu tố cần tính.","Báo Lỗi!",JOptionPane.OK_OPTION);
        }

    }

    /**
     * Action if Button NhapLai Clicked
     */
    private void btnNhapLai(){
        cbSelectElement.setSelectedIndex(0);
        txtResult.setText("");
        for (JTextField txt: txtElements) {
            txt.setText("");
        }
        cylinderHandle.initRVTable();
        this.setRTable(cylinderHandle.getRTable());
        this.setBuocGiai(null);
        imgEleAndEqua.setIcon(new ImageIcon(cylinderHandle.imageCylinderSemanticChange().getScaledInstance(620, 408, Image.SCALE_DEFAULT)));

    }

    /**
     * Action if Button ThongTin Clicked
     */
    private void btnThongTin(){
        JOptionPane.showMessageDialog(null, "- Đồ Án Tính Lăng Trụ Tròn Sử Dụng Mạng Ngữ Nghĩa" +
                        "\n- HUFI - Khoa CNTT - Lớp Trí Tuệ Nhân Tạo + JAVA" +
                        "\n- Thành Viên:" +
                        "\n+ 2001181078 - Nguyễn Trần Phương Duy - Trưởng Nhóm" +
                        "\n+ 2001181293 - Cao Quang Sơn" +
                        "\n+ 2001181291 - Ngô Thị Như Quỳnh" +
                        "\n+ 2001181437 - Phan Mai Như Ý" +
                        "\n- Email: duyntp2000@gmail.com" +
                        "\n- Github: chenjiinguyen", "Thông Tin Nhóm",
                JOptionPane.INFORMATION_MESSAGE,
                new ImageIcon(getClass().getResource("/CylinderSemantic/Resources/hufi.png")));
    }

    /**
     * Set RTable
     * @param RTable
     */
    private void setRTable(int [][] RTable){
        DefaultTableModel dataRTable = new DefaultTableModel();
        tblRTable.setModel(dataRTable);
        for (String str : new String[] {"Yếu Tố","CT1","CT2","CT3","CT4","CT5","CT6","CT7","CT8","CT9"}) {
            dataRTable.addColumn(str);
        }
        tblRTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        Object[] dataElements = new Object[] {"h","r","Co","So","Sq","Sxq","Stp","V","Cq"};
        for (int i = 0; i < RTable.length; i++) {
            Vector v = new Vector();
            v.add(dataElements[i]);
            for (int j = 0; j < RTable[i].length; j++)
                v.add(RTable[i][j]);
            dataRTable.addRow(v);
        }

        for (int i = 1; i < tblRTable.getColumnCount(); i++) {
            ColorRenderer cellStyle = new ColorRenderer();
            cellStyle.setHorizontalAlignment(JLabel.CENTER);
            tblRTable.getColumnModel().getColumn(i).setCellRenderer(cellStyle);
        }
    }

    /**
     * Set BuocGiai JList
     * @param lstBuocGiai
     */
    private void setBuocGiai(ArrayList<String> lstBuocGiai){
        Vector dataBuocGiai = new Vector();
        dataBuocGiai.clear();
        listBuocGiai.setListData(dataBuocGiai);
        if(lstBuocGiai != null)
        {
            for (String buocGiai: lstBuocGiai) {
                dataBuocGiai.add(buocGiai);
            }
        }

    }

    /**
     * Check TextField is Positive Real Numbers
     * @param evt
     * @param txtText
     */
    private  void checkNumber(KeyEvent evt,JTextField txtText){
        boolean dot = false;
        char vChar = evt.getKeyChar();
        if (txtText.getText().equals(""))
            dot = false;
        if (dot == false){
            if (vChar == '.') dot = true;
            else if (!(Character.isDigit(vChar)
                    || (vChar == KeyEvent.VK_BACK_SPACE)
                    || (vChar == KeyEvent.VK_DELETE))) {
                evt.consume();
            }
        } else {
            if (!(Character.isDigit(vChar)
                    || (vChar == KeyEvent.VK_BACK_SPACE)
                    || (vChar == KeyEvent.VK_DELETE))) {
                evt.consume();
            }
        }
    }

   /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JButton btnTinh;
    private javax.swing.JComboBox<String> cbSelectElement;
    private javax.swing.JLabel imgCylinder;
    private javax.swing.JLabel imgEleAndEqua;
    private javax.swing.JLabel lbCo;
    private javax.swing.JLabel lbResult;
    private javax.swing.JLabel lbSo;
    private javax.swing.JLabel lbSq;
    private javax.swing.JLabel lbStp;
    private javax.swing.JLabel lbSxq;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbV;
    private javax.swing.JLabel lbh;
    private javax.swing.JLabel lbr;
    private javax.swing.JList<String> listBuocGiai;
    private javax.swing.JPanel pnBuocGiai;
    private javax.swing.JPanel pnElements;
    private javax.swing.JPanel pnRTable;
    private javax.swing.JPanel pnResult;
    private javax.swing.JScrollPane scpBuocGiai;
    private javax.swing.JScrollPane scpRTable;
    private javax.swing.JTable tblRTable;
    private javax.swing.JTextField txtCo;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtSo;
    private javax.swing.JTextField txtSq;
    private javax.swing.JTextField txtStp;
    private javax.swing.JTextField txtSxq;
    private javax.swing.JTextField txtV;
    private javax.swing.JTextField txth;
    private javax.swing.JTextField txtr;
    // End of variables declaration//GEN-END:variables
}
